### ISSUE TITLE
file not exists in ubunto

### ISSUE THREAD

**Issue by shileislslsl** [docker/docker-credential-helpers#155]
I was tearing my hair out with an issue .
I run commend `docker-compose run --entrypoint /bin/bash hallsvr` 
and I enter the shell in container,
with commend `ls -al` 

```
total 44808
drwxr-xr-x    4 root     root          4096 Jul 11 10:51 .
drwxr-xr-x    4 root     root          4096 Jul 11 10:51 ..
-rwxr-xr-x    1 root     root           262 Jul 10 20:10 ddd.sh
-rwxr-xr-x    1 root     root          1849 Jul 10 20:11 docker-entrypoint.sh
-rwxr-xr-x    1 root     root      22927721 Jul 10 19:17 hallsvr
-rwxr-xr-x    1 root     root      22927721 Jul 11 09:25 hallsvr_new
drwxr-xr-x    2 root     root          4096 Jul 11 10:42 json
drwxr-xr-x    2 root     root          4096 Jul 11 10:42 log

```

but the commend `./hallsvr` returns `bash: ./hallsvr: No such file or directory`
anyone knows why and how to fix it? thanks!

for detail 
`docker -v`
`Docker version 18.09.7, build 2d0083d657`

`docker-compose --version`
`docker-compose version 1.21.2, build a133471`

`uname -a`
`Linux stone 4.18.0-25-generic #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by abhigyandwivedi** [comment]
What does echo $PATH gives you in docker's shell???

**Comment by thaJeztah** [comment]
This doesn't look related to the credentials-helper project (which is what this repository is for).

> but the commend ./hallsvr returns bash: ./hallsvr: No such file or directory anyone knows why and how to fix it? thanks!

Linux can print such messages in various situations, which can be confusing;

- make sure the `hallsvr` binary is built for the correct architecture
- if `hallsvr` is a dynamically linked binary; check if all dependencies are present (e.g. if a dll/so is missing, Linux can in some cases print "no such file or directory" (without printing _which_ file was not found).

closing this issue because of the above
