### ISSUE TITLE
Adding a list function which lists all the keychains from the credentials store

### ISSUE THREAD

**Issue by avaid96** [docker/docker-credential-helpers#17]
I'm trying to add functionality to [Notary](https://github.com/docker/notary) to store keychains in the local credentials store instead of on file (how it is currently). While I could get everything working fine with the functions you have here, Notary has a function to list all keys present on the machine which I need to support. I was wondering if we could add a list function to credentials-helpers since I'd like to keep all credentials functions in the same place- this repo. 

I have a way to list keychains on OSX and I can try to find a way to do it on Windows and D-Bus. Should I open a PR to try to integrate this functionality into credentials-helpers?

**Comment by calavera** [comment]
We had the same issue in the docker-engine and we opted for asking the credential helper for the server keys one by one because it was not possible to search lists in some stores:

https://github.com/docker/docker/blob/master/cliconfig/credentials/native_store.go#L60-L72

I think it'd be okay to add it here if there is a consistent way to get a list of credentials from those stores.

If we're just going to move the code I showed you here, I rather leave it in the consumers and keep this as simple as possible.

**Comment by calavera** [comment]
This was merged in master already.
