### ISSUE TITLE
'pass' based credential helper returns success when cred doesn't exist

### ISSUE THREAD

**Issue by nicks** [docker/docker-credential-helpers#220]
Repro steps:

```
echo "garbage" | go run ./pass/cmd/main.go get
```

Expected:
Exit code 1

Actual:
Exit code 0
{"ServerURL":"garbage","Username":"","Secret":""}

This is the root of cryptic errors like:

```
WARNING: could not erase credentials: error erasing credentials - err: exit status 1, out: `exit status 1: Error: docker-credential-helpers/[CRED_FOLDER_NAME] is not in the password store.` 
```

**Comment by ericpromislow** [comment]
The thing I find strange is that calling the underlying function `pass show security` would write `Error: security is not in the password store` to stderr and exit with status 1. But if I remember looking at this code a while ago, it's walking the raw filesystem.

This is related to the other problem that you can't use `docker-credential-pass list` to determine if the docker password-store has even been initialized because it returns `{}`, even if `pass (1)` hasn't been installed.
