### ISSUE TITLE
Build fails on 32 bit architectures

### ISSUE THREAD

**Issue by jmallach** [docker/docker-credential-helpers#57]
Hello,

The build fails on 32 bit architectures, with:

src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:108: type [1073741824]*C.char larger than address space
src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:108: type [1073741824]*C.char too large
src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:109: type [1073741824]*C.char larger than address space
src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:109: type [1073741824]*C.char too large

0.5.0 and an older git snapshot of 2016-09-06 fail. A snapshot of 2016-06-01 does build correctly.

Most possibly introduced in https://github.com/docker/docker-credential-helpers/commit/72661b31038ed4e34ebf5d65ac0b18cad96e5a8b

**Comment by n4ss** [comment]
I'm looking at Go documentation to convert portably a C.char pointer array to a Go CString slice. The documentation propose something working for 64bit only.

**Comment by jmallach** [comment]
Hi @n4ss, is there any progress on this front? Thanks!

**Comment by jmallach** [comment]
Hello,

This bug makes it hard to get docker compiled on 32 bit architectures. Is there anyone that can have a look at it? @n4ss, were you able to find a workaround?

**Comment by danieljoos** [comment]
Hi, there is an issue for this in the golang repository: https://github.com/golang/go/issues/13656
Looks like there will be a portable function for this in golang 1.10.
As a workaround:
* Limit the maximum number of list entries for the `List()` operation to 2^28 (268435456) (and change the slice conversion to use `[1<<28]*C.char`)
* Alternatively, use the `reflect.SliceHeader` struct, but the manual says, it is not portable (see https://golang.org/pkg/reflect/#SliceHeader). As far as I understood this is due to _possible_ changes of the slice format in future golang versions.

Cheers,
Daniel

**Comment by jmallach** [comment]
Hi Daniel,

Can a patch implementing your first suggestion be committed? I had tried [1<<28]*C.char when I first stumbled upon this, but I guess my calculation was way off.
