### ISSUE TITLE
how to uninstall on mac?

### ISSUE THREAD

**Issue by justechn** [docker/docker-credential-helpers#63]
I recently install docker for mac and when I run `docker login` it uses the keychain by default. I would like it to use the .docker/config.json by default. How do I either uninstall the keychain helper, or tell docker login to use the config.json file?

Why you might ask do I want to do this? I am using minikube and it needs access to our private docker images. I can send minikube the auth key, but only if it is in .docker/config.json

**Comment by ebriney** [comment]
@justechn in [last edge version](https://download.docker.com/mac/edge/Docker.dmg) there is an option to do that, it will be include in the next stable this month too.

**Comment by thaJeztah** [comment]
There's a checkbox now, as mentioned, so let me close this. I would recommend opening an issue with minikube as well, because storing in `.docker/config.json` is really insecure (password is stored unencrypted); perhaps they can use the credential-helpers to get the credentials instead.

<img width="351" alt="screen shot 2017-06-15 at 02 11 41" src="https://user-images.githubusercontent.com/1804568/27221623-7c12c514-5289-11e7-84d6-101c8b3230cc.png">


closing, but feel free to continue the conversation 👍
